### ISSUE TITLE
opencores-scraper stuck while parsing www.opencores.org/project,or1k  

### ISSUE THREAD

**Issue by NoSuchProcess** [fabriziotappero/opencores-scraper#1]
www.opencores.org/project,or1k is broken for a long time, it's main page says: "Sorry! This site is experiencing technical difficulties.", so opencores-scraper downloads it's page again and again:
```
[Fri Dec  8 14:49:59 2017] 
Downloading HTML from: http://www.opencores.org/project,or1k
WARNING. Getting some http error. Trying again...
[Fri Dec  8 14:50:00 2017] 
Downloading HTML from: http://www.opencores.org/project,or1k
WARNING. Getting some http error. Trying again...
```

There should be a way to skip downloading such repos.

**Comment by fabriziotappero** [comment]
Hi Sergey,
I see, it is certainly possible.

How many times is the current version trying to download it? what
consequences does a dead project generate?

Regards
Fabrizio

**Comment by NoSuchProcess** [comment]
> How many times is the current version trying to download it?

It tries to download it in a endless loop. I had to interrupt the program. There are a couple of `while True: ... ` in the code, so i added a couple of quick an dirty workarounds to my copy to have the work done.

> what consequences does a dead project generate?

Just have a look at the www.opencores.org/project,or1k, it is still broken and produces a kind of 404 page. Maybe this is the only broken project.

**Comment by fabriziotappero** [comment]
Hi Sergey,
it would be great if you could submit a patch with the "try" or with a
solution where it attepts to detect a 404 error. Would you be interested?

cheers
fabrizio

**Comment by NoSuchProcess** [comment]
With pleasure. Have a look at the PR.

Regards,
Sergey

**Comment by fabriziotappero** [comment]
cheers
Fabrizio
